
classdef MultiPriorityTask < ros.Message
    %MultiPriorityTask MATLAB implementation of lwr_controllers/MultiPriorityTask
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'lwr_controllers/MultiPriorityTask' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '42e011fbf13e33d6ed6e65ac7a0bdf63' % The MD5 Checksum of the message definition
        PropertyList = { 'Links' 'Tasks' } % List of non-constant message properties
        ROSPropertyList = { 'links' 'tasks' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Links
        Tasks
    end
    methods
        function set.Links(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MultiPriorityTask', 'Links');
            obj.Links = int32(val);
        end
        function set.Tasks(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MultiPriorityTask', 'Tasks');
            obj.Tasks = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.lwr_controllers.MultiPriorityTask.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.lwr_controllers.MultiPriorityTask(strObj);
        end
    end
end
