
classdef Stiffness < ros.Message
    %Stiffness MATLAB implementation of lwr_controllers/Stiffness
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'lwr_controllers/Stiffness' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '88d995302418aa13534aa14fc9aeed94' % The MD5 Checksum of the message definition
        PropertyList = { 'X' 'Y' 'Z' 'Rx' 'Ry' 'Rz' } % List of non-constant message properties
        ROSPropertyList = { 'x' 'y' 'z' 'rx' 'ry' 'rz' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        X
        Y
        Z
        Rx
        Ry
        Rz
    end
    methods
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'X');
            obj.X = double(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'Y');
            obj.Y = double(val);
        end
        function set.Z(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'Z');
            obj.Z = double(val);
        end
        function set.Rx(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'Rx');
            obj.Rx = double(val);
        end
        function set.Ry(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'Ry');
            obj.Ry = double(val);
        end
        function set.Rz(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Stiffness', 'Rz');
            obj.Rz = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.lwr_controllers.Stiffness.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.lwr_controllers.Stiffness(strObj);
        end
    end
end
