
classdef PoseRPY < ros.Message
    %PoseRPY MATLAB implementation of lwr_controllers/PoseRPY
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'lwr_controllers/PoseRPY' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ac4defc6a342778de62991685c2a0dda' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'Orientation' 'Id' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'orientation' 'id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.lwr_controllers.RPY' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        Orientation
        Id
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'PoseRPY', 'Position')
            obj.Position = val;
        end
        function set.Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.lwr_controllers.RPY'};
            validateattributes(val, validClasses, validAttributes, 'PoseRPY', 'Orientation')
            obj.Orientation = val;
        end
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PoseRPY', 'Id');
            obj.Id = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.lwr_controllers.PoseRPY.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.lwr_controllers.PoseRPY(strObj);
        end
    end
end
