
classdef SetCartesianImpedanceCommandRequest < ros.Message
    %SetCartesianImpedanceCommandRequest MATLAB implementation of lwr_controllers/SetCartesianImpedanceCommandRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'lwr_controllers/SetCartesianImpedanceCommandRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cc36264319f44d204c2ace0744aa21ee' % The MD5 Checksum of the message definition
        PropertyList = { 'Command' } % List of non-constant message properties
        ROSPropertyList = { 'command' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.lwr_controllers.CartesianImpedancePoint' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Command
    end
    methods
        function set.Command(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.lwr_controllers.CartesianImpedancePoint'};
            validateattributes(val, validClasses, validAttributes, 'SetCartesianImpedanceCommandRequest', 'Command')
            obj.Command = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.lwr_controllers.SetCartesianImpedanceCommandRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.lwr_controllers.SetCartesianImpedanceCommandRequest(strObj);
        end
    end
end
