//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class RotJointsMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/RotJoints";
        public override string RosMessageName => k_RosMessageName;

        public float a1_joint;
        public float a2_joint;
        public float a3_joint;
        public float a4_joint;
        public float a5_joint;
        public float a6_joint;
        public float e1_joint;

        public RotJointsMsg()
        {
            this.a1_joint = 0.0f;
            this.a2_joint = 0.0f;
            this.a3_joint = 0.0f;
            this.a4_joint = 0.0f;
            this.a5_joint = 0.0f;
            this.a6_joint = 0.0f;
            this.e1_joint = 0.0f;
        }

        public RotJointsMsg(float a1_joint, float a2_joint, float a3_joint, float a4_joint, float a5_joint, float a6_joint, float e1_joint)
        {
            this.a1_joint = a1_joint;
            this.a2_joint = a2_joint;
            this.a3_joint = a3_joint;
            this.a4_joint = a4_joint;
            this.a5_joint = a5_joint;
            this.a6_joint = a6_joint;
            this.e1_joint = e1_joint;
        }

        public static RotJointsMsg Deserialize(MessageDeserializer deserializer) => new RotJointsMsg(deserializer);

        private RotJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.a1_joint);
            deserializer.Read(out this.a2_joint);
            deserializer.Read(out this.a3_joint);
            deserializer.Read(out this.a4_joint);
            deserializer.Read(out this.a5_joint);
            deserializer.Read(out this.a6_joint);
            deserializer.Read(out this.e1_joint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a1_joint);
            serializer.Write(this.a2_joint);
            serializer.Write(this.a3_joint);
            serializer.Write(this.a4_joint);
            serializer.Write(this.a5_joint);
            serializer.Write(this.a6_joint);
            serializer.Write(this.e1_joint);
        }

        public override string ToString()
        {
            return "RotJointsMsg: " +
            "\na1_joint: " + a1_joint.ToString() +
            "\na2_joint: " + a2_joint.ToString() +
            "\na3_joint: " + a3_joint.ToString() +
            "\na4_joint: " + a4_joint.ToString() +
            "\na5_joint: " + a5_joint.ToString() +
            "\na6_joint: " + a6_joint.ToString() +
            "\ne1_joint: " + e1_joint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
